### ISSUE TITLE
Mail author is truncated (19 character length)

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis-gmail#1]
> jarvis: Waiting to hear 'jarvis'
> Jean-Marc: jarvis
> jarvis: Oui ?
> Jean-Marc: ?est-ce que j'ai des mails non-lus
> jarvis: Je regarde...
> jarvis: Vous avez 1 emails non lus, le dernier est de **_Microsoft Online Se._**

In this case I received an e-mail of "Microsoft Online Services Team"

**Comment by alexylem** [comment]
Tu peux tester manuellement? (marque les mails arrivés après comme lus)

``` shell
curl -u $gmail_username:$gmail_password --silent "https://mail.google.com/mail/feed/atom"
```

**Comment by wikijm** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<feed version="0.3" xmlns="http://purl.org/atom/ns#">

<tagline>New messages in your Gmail Inbox</tagline>
<fullcount>1</fullcount>
<link rel="alternate" href="https://mail.google.com/mail" type="text/html" />

<author>
    <name>Microsoft Online Se.</name>
    <email>msonlineservicesteam@microsoftonline.com</email>
</author>
```

C'est GMail qui est à l'origine de la limitation apparemment.

**Comment by alexylem** [comment]
2 possibilités:
- Soit on ferme le ticket et on vit avec
- Soit j'ajoute une option pour désactiver cette information de qui a envoyé le dernier email (ca peut ne pas plaire à tout le monde)

**Comment by wikijm** [comment]
On va vivre avec. Au moins le problème est connu et référencé 👍
