### ISSUE TITLE
UNAUTHORIZED

### ISSUE THREAD

**Issue by yanngeny** [alexylem/jarvis-gmail#2]
Bonjour alors voilà lorsque je demande de vérifier mes mails le plugin me mets une erreur UNAUTHORIZED savez vous à quoi cela est dû ?

**Comment by alexylem** [comment]
Tu n'as pas configuré le plugin, ou tes identifiants ne sont pas valides.
C'est dans Jarvis > Plugins > Installed > Gmail > Configure

**Comment by yanngeny** [comment]
Merci en fait je les simplement réinstallé et tout est rentré dans l'ordre
