### ISSUE TITLE
Pas possible de lire le feed gmail - not authorized

### ISSUE THREAD

**Issue by wormch** [alexylem/jarvis-gmail#3]
Il n'est pas possible de lire le feed si dans le options de Google on active pas les "Applications moins sures" (lien: https://www.google.com/settings/security/lesssecureapps)

Éventuellement adopter quelque chose comme ça -> https://github.com/soulseekah/bash-utils/tree/master/google-oauth2

J'ai aussi découvert que si dans le mot de passe ce trouve le symbole du dollar '$', ça ne marche pas

**Comment by alexylem** [comment]
Merci beaucoup @wormch pour ces informations.
C'était dans mon cas activé sans que j'ai à le changer. Mais pour d'autres ca peut ne pas être le cas. Je vais le rajouter comme une étape à vérifier lors de l'installation.
Oui pour le `$` c'est très probablement un bug, je vais le corriger.
Je regarderai aussi ta proposition pour l'authentification. sécurisée.

**Comment by alexylem** [comment]
Pour les `$` dans le mot de passe, il faut remplacer dans la configuration du plugin les doubles quotes par des simples quotes:

**config.sh**
```shell
gmail_password='my$password'
```
